services:
  backend:
    build:
      context: ./student-job-tracker-backend
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: student_job_tracker
      DB_USER: dev
      DB_PASSWORD: "1234"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./student-job-tracker-frontend
    ports:
      - "3000:80"

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: student_job_tracker
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d student_job_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
